### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by egorovivannn** [Yu-zhengbo/Seg-Road#1]
Thank you for your great work. I am glad I found the implementation of your awesome paper. But would you please provide us with the pretrained weights that you got during your experiments? I would like to use them for my academic research in the field of satellite image segmentation

**Comment by Yu-zhengbo** [comment]
Thank you for being interested in our work, but I got a new computer this September, and only the relevant code has been saved from the previous project, the model weights have been deleted as well as the dataset and so on. However, the relevant code of this project is relatively complete at present, and you can do the relevant training on your computing resources. If you encounter some problems, please feel free to leave a comment.

**Comment by Yu-zhengbo** [comment]
> Thank you for your great work. I am glad I found the implementation of your awesome paper. But would you please provide us with the pretrained weights that you got during your experiments? I would like to use them for my academic research in the field of satellite image segmentation

Thank you for being interested in our work, but I got a new computer this September, and only the relevant code has been saved from the previous project, the model weights have been deleted as well as the dataset and so on. However, the relevant code of this project is relatively complete at present, and you can do the relevant training on your computing resources. If you encounter some problems, please feel free to leave a comment.

Translated with www.DeepL.com/Translator (free version)

**Comment by Yu-zhengbo** [comment]
> Thank you for your great work. I am glad I found the implementation of your awesome paper. But would you please provide us with the pretrained weights that you got during your experiments? I would like to use them for my academic research in the field of satellite image segmentation

Thank you for being interested in our work, but I got a new computer this September, and only the relevant code has been saved from the previous project, the model weights have been deleted as well as the dataset and so on. However, the relevant code of this project is relatively complete at present, and you can do the relevant training on your computing resources. If you encounter some problems, please feel free to leave a comment.

**Comment by egorovivannn** [comment]
Thank you for the answer. 
But why didnt you submit your work in a benchmark such as that [https://paperswithcode.com/task/road-segementation](url) ?
You could make much more contribution in the filed and other researcher could do more research based on your great work

**Comment by Yu-zhengbo** [comment]
> Thank you for the answer. But why didnt you submit your work in a benchmark such as that [https://paperswithcode.com/task/road-segementation](url) ? You could make much more contribution in the filed and other researcher could do more research based on your great work

Thanks for the advice, I didn't focus too much on open-sourcing the code in my graduate studies until recently. Meanwhile, I have recently re-planned to do further research on road extraction from remote sensing imagery, and I will upload the relevant data to paperwithcode!
